### ISSUE TITLE
Graphic/audio experience stuff

### ISSUE THREAD

**Issue by DavidBystroem** [Kosuiroom/Tofuchomp#1]
- Big enemy "IceCeal":
1.  Not Playing "Attack "Animation when attacking - done
2. The attack is not the red ball spread attack sprite - done
3. No explosion death - done
4. Death sound - done
5. No damage indication (flickering of a color?) (as they seem to have more health?) - done, moved the rest to a new issue

- Small Enemy "BreadCat"
1. If they are not shooting anything then maybe just have the "Idle" animation? (subjective thing) - Done
2.  No explosion death - done
3. Death Sound - done

- Boss
1.  No damage indication
2. Switch to the "Attack" animation briefly when they shoot the laser - done
4. If the laser is shooting straight maybe we should have it smaller?? - moved to another issue
5. A death sound (same meow sound when its health is 0)? - done
6. Victory jingle sound after it is dead? - moved to another issue

- Player
1. Are we to have a big laser or just regular and spread? (the big one is the mushroom mosquito sprite still) - done
2. Players spread is the small laser and not the blue spread attack sprite - done
3. No Damage indication (if more than 1 life) - only one life so no dmg indication
4. No Explosion death - moved to new issue

**Comment by redines** [comment]
För många issues I en issue :)

**Comment by redines** [comment]
Big laser är för bossen

**Comment by redines** [comment]
If the laser is shooting straight maybe we should have it smaller??

I think this should be quite big since at the moment the boss can not shoot their regular spread exactly at the center for some reasons so making this big will forc the player to move and potentially get hit by the other spread lasers

**Comment by redines** [comment]
No Damage indication (if more than 1 life) for player

my first idead is that we only have one life, and then the player has to retry, at the moment this is easier. otherwise we need to implement a more advanced health system which will expand the game and also add ui components for it

**Comment by redines** [comment]
- Small Enemy "BreadCat"
1. If they are not shooting anything then maybe just have the "Idle" animation? (subjective thing) - Done
set it to Idle animation

**Comment by redines** [comment]
all issues in this is fixed or moved to a separate issue
