### ISSUE TITLE
Game(play)

### ISSUE THREAD

**Issue by DavidBystroem** [Kosuiroom/Tofuchomp#2]
- Player
1.  Seems to take no damage whatsoever and can't die
2. Without doing anything the output keeps printing out "player hit big enemy". Mean anything special?

- End credit
1.  No "Final Score" score being printed

**Comment by redines** [comment]
1. Ändra spelarens armor variable till något lägre
2. det är debug output som ingen annan skimmer se
3. ha ett issue/issue :) för annars blir det svårt att följa uppnett exakt problem
